//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Ce code source a été automatiquement généré par xsd, Version=4.8.3928.0.
// 
namespace simbrief {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class notam {
        
        private string source_idField;
        
        private string account_idField;
        
        private string notam_idField;
        
        private string location_idField;
        
        private string location_icaoField;
        
        private string location_nameField;
        
        private string location_typeField;
        
        private string date_createdField;
        
        private string date_effectiveField;
        
        private string date_expireField;
        
        private string date_expire_is_estimatedField;
        
        private string date_modifiedField;
        
        private string notam_scheduleField;
        
        private string notam_htmlField;
        
        private string notam_textField;
        
        private string notam_rawField;
        
        private string notam_nrcField;
        
        private string notam_qcodeField;
        
        private string notam_qcode_categoryField;
        
        private string notam_qcode_subjectField;
        
        private string notam_qcode_statusField;
        
        private string notam_is_obstacleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string source_id {
            get {
                return this.source_idField;
            }
            set {
                this.source_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string account_id {
            get {
                return this.account_idField;
            }
            set {
                this.account_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string notam_id {
            get {
                return this.notam_idField;
            }
            set {
                this.notam_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string location_id {
            get {
                return this.location_idField;
            }
            set {
                this.location_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string location_icao {
            get {
                return this.location_icaoField;
            }
            set {
                this.location_icaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string location_name {
            get {
                return this.location_nameField;
            }
            set {
                this.location_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string location_type {
            get {
                return this.location_typeField;
            }
            set {
                this.location_typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string date_created {
            get {
                return this.date_createdField;
            }
            set {
                this.date_createdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string date_effective {
            get {
                return this.date_effectiveField;
            }
            set {
                this.date_effectiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string date_expire {
            get {
                return this.date_expireField;
            }
            set {
                this.date_expireField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string date_expire_is_estimated {
            get {
                return this.date_expire_is_estimatedField;
            }
            set {
                this.date_expire_is_estimatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string date_modified {
            get {
                return this.date_modifiedField;
            }
            set {
                this.date_modifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string notam_schedule {
            get {
                return this.notam_scheduleField;
            }
            set {
                this.notam_scheduleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string notam_html {
            get {
                return this.notam_htmlField;
            }
            set {
                this.notam_htmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string notam_text {
            get {
                return this.notam_textField;
            }
            set {
                this.notam_textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string notam_raw {
            get {
                return this.notam_rawField;
            }
            set {
                this.notam_rawField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string notam_nrc {
            get {
                return this.notam_nrcField;
            }
            set {
                this.notam_nrcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string notam_qcode {
            get {
                return this.notam_qcodeField;
            }
            set {
                this.notam_qcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string notam_qcode_category {
            get {
                return this.notam_qcode_categoryField;
            }
            set {
                this.notam_qcode_categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string notam_qcode_subject {
            get {
                return this.notam_qcode_subjectField;
            }
            set {
                this.notam_qcode_subjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string notam_qcode_status {
            get {
                return this.notam_qcode_statusField;
            }
            set {
                this.notam_qcode_statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string notam_is_obstacle {
            get {
                return this.notam_is_obstacleField;
            }
            set {
                this.notam_is_obstacleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class fix {
        
        private string identField;
        
        private string nameField;
        
        private string typeField;
        
        private string icao_regionField;
        
        private string frequencyField;
        
        private double pos_latField;
        
        private bool pos_latFieldSpecified;
        
        private double pos_longField;
        
        private bool pos_longFieldSpecified;
        
        private string stageField;
        
        private string via_airwayField;
        
        private string is_sid_starField;
        
        private string distanceField;
        
        private string track_trueField;
        
        private string track_magField;
        
        private string heading_trueField;
        
        private string heading_magField;
        
        private string altitude_feetField;
        
        private string ind_airspeedField;
        
        private string true_airspeedField;
        
        private string machField;
        
        private string mach_thousandthsField;
        
        private string wind_componentField;
        
        private string groundspeedField;
        
        private string time_legField;
        
        private string time_totalField;
        
        private string fuel_flowField;
        
        private string fuel_legField;
        
        private string fuel_totalusedField;
        
        private string fuel_min_onboardField;
        
        private string fuel_plan_onboardField;
        
        private string oatField;
        
        private string oat_isa_devField;
        
        private string wind_dirField;
        
        private string wind_spdField;
        
        private string shearField;
        
        private string tropopause_feetField;
        
        private string ground_heightField;
        
        private string firField;
        
        private string fir_unitsField;
        
        private string fir_valid_levelsField;
        
        private string moraField;
        
        private fixLevel[] wind_dataField;
        
        private fixFir[] fir_crossingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ident {
            get {
                return this.identField;
            }
            set {
                this.identField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string icao_region {
            get {
                return this.icao_regionField;
            }
            set {
                this.icao_regionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string frequency {
            get {
                return this.frequencyField;
            }
            set {
                this.frequencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double pos_lat {
            get {
                return this.pos_latField;
            }
            set {
                this.pos_latField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pos_latSpecified {
            get {
                return this.pos_latFieldSpecified;
            }
            set {
                this.pos_latFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double pos_long {
            get {
                return this.pos_longField;
            }
            set {
                this.pos_longField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pos_longSpecified {
            get {
                return this.pos_longFieldSpecified;
            }
            set {
                this.pos_longFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string stage {
            get {
                return this.stageField;
            }
            set {
                this.stageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string via_airway {
            get {
                return this.via_airwayField;
            }
            set {
                this.via_airwayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string is_sid_star {
            get {
                return this.is_sid_starField;
            }
            set {
                this.is_sid_starField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string track_true {
            get {
                return this.track_trueField;
            }
            set {
                this.track_trueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string track_mag {
            get {
                return this.track_magField;
            }
            set {
                this.track_magField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string heading_true {
            get {
                return this.heading_trueField;
            }
            set {
                this.heading_trueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string heading_mag {
            get {
                return this.heading_magField;
            }
            set {
                this.heading_magField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string altitude_feet {
            get {
                return this.altitude_feetField;
            }
            set {
                this.altitude_feetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ind_airspeed {
            get {
                return this.ind_airspeedField;
            }
            set {
                this.ind_airspeedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string true_airspeed {
            get {
                return this.true_airspeedField;
            }
            set {
                this.true_airspeedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mach {
            get {
                return this.machField;
            }
            set {
                this.machField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mach_thousandths {
            get {
                return this.mach_thousandthsField;
            }
            set {
                this.mach_thousandthsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wind_component {
            get {
                return this.wind_componentField;
            }
            set {
                this.wind_componentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string groundspeed {
            get {
                return this.groundspeedField;
            }
            set {
                this.groundspeedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string time_leg {
            get {
                return this.time_legField;
            }
            set {
                this.time_legField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string time_total {
            get {
                return this.time_totalField;
            }
            set {
                this.time_totalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fuel_flow {
            get {
                return this.fuel_flowField;
            }
            set {
                this.fuel_flowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fuel_leg {
            get {
                return this.fuel_legField;
            }
            set {
                this.fuel_legField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fuel_totalused {
            get {
                return this.fuel_totalusedField;
            }
            set {
                this.fuel_totalusedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fuel_min_onboard {
            get {
                return this.fuel_min_onboardField;
            }
            set {
                this.fuel_min_onboardField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fuel_plan_onboard {
            get {
                return this.fuel_plan_onboardField;
            }
            set {
                this.fuel_plan_onboardField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string oat {
            get {
                return this.oatField;
            }
            set {
                this.oatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string oat_isa_dev {
            get {
                return this.oat_isa_devField;
            }
            set {
                this.oat_isa_devField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wind_dir {
            get {
                return this.wind_dirField;
            }
            set {
                this.wind_dirField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wind_spd {
            get {
                return this.wind_spdField;
            }
            set {
                this.wind_spdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string shear {
            get {
                return this.shearField;
            }
            set {
                this.shearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tropopause_feet {
            get {
                return this.tropopause_feetField;
            }
            set {
                this.tropopause_feetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ground_height {
            get {
                return this.ground_heightField;
            }
            set {
                this.ground_heightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fir {
            get {
                return this.firField;
            }
            set {
                this.firField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fir_units {
            get {
                return this.fir_unitsField;
            }
            set {
                this.fir_unitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fir_valid_levels {
            get {
                return this.fir_valid_levelsField;
            }
            set {
                this.fir_valid_levelsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mora {
            get {
                return this.moraField;
            }
            set {
                this.moraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("level", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public fixLevel[] wind_data {
            get {
                return this.wind_dataField;
            }
            set {
                this.wind_dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("fir", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public fixFir[] fir_crossing {
            get {
                return this.fir_crossingField;
            }
            set {
                this.fir_crossingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class fixLevel {
        
        private string altitudeField;
        
        private string wind_dirField;
        
        private string wind_spdField;
        
        private string oatField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string altitude {
            get {
                return this.altitudeField;
            }
            set {
                this.altitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wind_dir {
            get {
                return this.wind_dirField;
            }
            set {
                this.wind_dirField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wind_spd {
            get {
                return this.wind_spdField;
            }
            set {
                this.wind_spdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string oat {
            get {
                return this.oatField;
            }
            set {
                this.oatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class fixFir {
        
        private string fir_icaoField;
        
        private string fir_nameField;
        
        private double pos_lat_entryField;
        
        private bool pos_lat_entryFieldSpecified;
        
        private double pos_long_entryField;
        
        private bool pos_long_entryFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fir_icao {
            get {
                return this.fir_icaoField;
            }
            set {
                this.fir_icaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fir_name {
            get {
                return this.fir_nameField;
            }
            set {
                this.fir_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double pos_lat_entry {
            get {
                return this.pos_lat_entryField;
            }
            set {
                this.pos_lat_entryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pos_lat_entrySpecified {
            get {
                return this.pos_lat_entryFieldSpecified;
            }
            set {
                this.pos_lat_entryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double pos_long_entry {
            get {
                return this.pos_long_entryField;
            }
            set {
                this.pos_long_entryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pos_long_entrySpecified {
            get {
                return this.pos_long_entryFieldSpecified;
            }
            set {
                this.pos_long_entryFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class pdf {
        
        private string nameField;
        
        private string linkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class OFP {
        
        private string takeoff_altnField;
        
        private string enroute_altnField;
        
        private string etopsField;
        
        private string tracksField;
        
        private string vatsim_prefileField;
        
        private string ivao_prefileField;
        
        private string pilotedge_prefileField;
        
        private string poscon_prefileField;
        
        private string map_dataField;
        
        private OFPGeneral generalField;
        
        private OFPOrigin originField;
        
        private OFPDestination destinationField;
        
        private OFPAlternate alternateField;
        
        private fix[] alternate_navlogField;
        
        private fix[] navlogField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string takeoff_altn {
            get {
                return this.takeoff_altnField;
            }
            set {
                this.takeoff_altnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string enroute_altn {
            get {
                return this.enroute_altnField;
            }
            set {
                this.enroute_altnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string etops {
            get {
                return this.etopsField;
            }
            set {
                this.etopsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tracks {
            get {
                return this.tracksField;
            }
            set {
                this.tracksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string vatsim_prefile {
            get {
                return this.vatsim_prefileField;
            }
            set {
                this.vatsim_prefileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ivao_prefile {
            get {
                return this.ivao_prefileField;
            }
            set {
                this.ivao_prefileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pilotedge_prefile {
            get {
                return this.pilotedge_prefileField;
            }
            set {
                this.pilotedge_prefileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string poscon_prefile {
            get {
                return this.poscon_prefileField;
            }
            set {
                this.poscon_prefileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string map_data {
            get {
                return this.map_dataField;
            }
            set {
                this.map_dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OFPGeneral general {
            get {
                return this.generalField;
            }
            set {
                this.generalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OFPOrigin origin {
            get {
                return this.originField;
            }
            set {
                this.originField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OFPDestination destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OFPAlternate alternate {
            get {
                return this.alternateField;
            }
            set {
                this.alternateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("fix", IsNullable=false)]
        public fix[] alternate_navlog {
            get {
                return this.alternate_navlogField;
            }
            set {
                this.alternate_navlogField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("fix", IsNullable=false)]
        public fix[] navlog {
            get {
                return this.navlogField;
            }
            set {
                this.navlogField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class OFPGeneral {
        
        private string releaseField;
        
        private string icao_airlineField;
        
        private string flight_numberField;
        
        private string is_etopsField;
        
        private string dx_rmkField;
        
        private string sys_rmkField;
        
        private string is_detailed_profileField;
        
        private string cruise_profileField;
        
        private string climb_profileField;
        
        private string descent_profileField;
        
        private string alternate_profileField;
        
        private string reserve_profileField;
        
        private string costindexField;
        
        private string cont_ruleField;
        
        private string initial_altitudeField;
        
        private string stepclimb_stringField;
        
        private string avg_temp_devField;
        
        private string avg_tropopauseField;
        
        private string avg_wind_compField;
        
        private string avg_wind_dirField;
        
        private string avg_wind_spdField;
        
        private string gc_distanceField;
        
        private string route_distanceField;
        
        private string air_distanceField;
        
        private string total_burnField;
        
        private string cruise_tasField;
        
        private string cruise_machField;
        
        private string passengersField;
        
        private string routeField;
        
        private string route_ifpsField;
        
        private string route_navigraphField;
        
        private string sid_identField;
        
        private string sid_transField;
        
        private string star_identField;
        
        private string star_transField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string release {
            get {
                return this.releaseField;
            }
            set {
                this.releaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string icao_airline {
            get {
                return this.icao_airlineField;
            }
            set {
                this.icao_airlineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string flight_number {
            get {
                return this.flight_numberField;
            }
            set {
                this.flight_numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string is_etops {
            get {
                return this.is_etopsField;
            }
            set {
                this.is_etopsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dx_rmk {
            get {
                return this.dx_rmkField;
            }
            set {
                this.dx_rmkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sys_rmk {
            get {
                return this.sys_rmkField;
            }
            set {
                this.sys_rmkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string is_detailed_profile {
            get {
                return this.is_detailed_profileField;
            }
            set {
                this.is_detailed_profileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cruise_profile {
            get {
                return this.cruise_profileField;
            }
            set {
                this.cruise_profileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string climb_profile {
            get {
                return this.climb_profileField;
            }
            set {
                this.climb_profileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descent_profile {
            get {
                return this.descent_profileField;
            }
            set {
                this.descent_profileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string alternate_profile {
            get {
                return this.alternate_profileField;
            }
            set {
                this.alternate_profileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reserve_profile {
            get {
                return this.reserve_profileField;
            }
            set {
                this.reserve_profileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string costindex {
            get {
                return this.costindexField;
            }
            set {
                this.costindexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cont_rule {
            get {
                return this.cont_ruleField;
            }
            set {
                this.cont_ruleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string initial_altitude {
            get {
                return this.initial_altitudeField;
            }
            set {
                this.initial_altitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string stepclimb_string {
            get {
                return this.stepclimb_stringField;
            }
            set {
                this.stepclimb_stringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string avg_temp_dev {
            get {
                return this.avg_temp_devField;
            }
            set {
                this.avg_temp_devField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string avg_tropopause {
            get {
                return this.avg_tropopauseField;
            }
            set {
                this.avg_tropopauseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string avg_wind_comp {
            get {
                return this.avg_wind_compField;
            }
            set {
                this.avg_wind_compField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string avg_wind_dir {
            get {
                return this.avg_wind_dirField;
            }
            set {
                this.avg_wind_dirField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string avg_wind_spd {
            get {
                return this.avg_wind_spdField;
            }
            set {
                this.avg_wind_spdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gc_distance {
            get {
                return this.gc_distanceField;
            }
            set {
                this.gc_distanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string route_distance {
            get {
                return this.route_distanceField;
            }
            set {
                this.route_distanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string air_distance {
            get {
                return this.air_distanceField;
            }
            set {
                this.air_distanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string total_burn {
            get {
                return this.total_burnField;
            }
            set {
                this.total_burnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cruise_tas {
            get {
                return this.cruise_tasField;
            }
            set {
                this.cruise_tasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cruise_mach {
            get {
                return this.cruise_machField;
            }
            set {
                this.cruise_machField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passengers {
            get {
                return this.passengersField;
            }
            set {
                this.passengersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string route {
            get {
                return this.routeField;
            }
            set {
                this.routeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string route_ifps {
            get {
                return this.route_ifpsField;
            }
            set {
                this.route_ifpsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string route_navigraph {
            get {
                return this.route_navigraphField;
            }
            set {
                this.route_navigraphField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sid_ident {
            get {
                return this.sid_identField;
            }
            set {
                this.sid_identField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sid_trans {
            get {
                return this.sid_transField;
            }
            set {
                this.sid_transField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string star_ident {
            get {
                return this.star_identField;
            }
            set {
                this.star_identField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string star_trans {
            get {
                return this.star_transField;
            }
            set {
                this.star_transField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class OFPOrigin {
        
        private string icao_codeField;
        
        private string iata_codeField;
        
        private string faa_codeField;
        
        private string icao_regionField;
        
        private string elevationField;
        
        private double pos_latField;
        
        private bool pos_latFieldSpecified;
        
        private double pos_longField;
        
        private bool pos_longFieldSpecified;
        
        private string nameField;
        
        private string timezoneField;
        
        private string plan_rwyField;
        
        private int trans_altField;
        
        private bool trans_altFieldSpecified;
        
        private int trans_levelField;
        
        private bool trans_levelFieldSpecified;
        
        private string metarField;
        
        private string metar_timeField;
        
        private string metar_categoryField;
        
        private string metar_visibilityField;
        
        private string metar_ceilingField;
        
        private string tafField;
        
        private string taf_timeField;
        
        private OFPOriginAtis[] atisField;
        
        private notam[] notamField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string icao_code {
            get {
                return this.icao_codeField;
            }
            set {
                this.icao_codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string iata_code {
            get {
                return this.iata_codeField;
            }
            set {
                this.iata_codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string faa_code {
            get {
                return this.faa_codeField;
            }
            set {
                this.faa_codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string icao_region {
            get {
                return this.icao_regionField;
            }
            set {
                this.icao_regionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string elevation {
            get {
                return this.elevationField;
            }
            set {
                this.elevationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double pos_lat {
            get {
                return this.pos_latField;
            }
            set {
                this.pos_latField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pos_latSpecified {
            get {
                return this.pos_latFieldSpecified;
            }
            set {
                this.pos_latFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double pos_long {
            get {
                return this.pos_longField;
            }
            set {
                this.pos_longField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pos_longSpecified {
            get {
                return this.pos_longFieldSpecified;
            }
            set {
                this.pos_longFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string timezone {
            get {
                return this.timezoneField;
            }
            set {
                this.timezoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string plan_rwy {
            get {
                return this.plan_rwyField;
            }
            set {
                this.plan_rwyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int trans_alt {
            get {
                return this.trans_altField;
            }
            set {
                this.trans_altField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool trans_altSpecified {
            get {
                return this.trans_altFieldSpecified;
            }
            set {
                this.trans_altFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int trans_level {
            get {
                return this.trans_levelField;
            }
            set {
                this.trans_levelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool trans_levelSpecified {
            get {
                return this.trans_levelFieldSpecified;
            }
            set {
                this.trans_levelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string metar {
            get {
                return this.metarField;
            }
            set {
                this.metarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string metar_time {
            get {
                return this.metar_timeField;
            }
            set {
                this.metar_timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string metar_category {
            get {
                return this.metar_categoryField;
            }
            set {
                this.metar_categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string metar_visibility {
            get {
                return this.metar_visibilityField;
            }
            set {
                this.metar_visibilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string metar_ceiling {
            get {
                return this.metar_ceilingField;
            }
            set {
                this.metar_ceilingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string taf {
            get {
                return this.tafField;
            }
            set {
                this.tafField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string taf_time {
            get {
                return this.taf_timeField;
            }
            set {
                this.taf_timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("atis", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OFPOriginAtis[] atis {
            get {
                return this.atisField;
            }
            set {
                this.atisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("notam")]
        public notam[] notam {
            get {
                return this.notamField;
            }
            set {
                this.notamField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class OFPOriginAtis {
        
        private string networkField;
        
        private string issuedField;
        
        private string letterField;
        
        private string phoneticField;
        
        private string typeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string network {
            get {
                return this.networkField;
            }
            set {
                this.networkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string issued {
            get {
                return this.issuedField;
            }
            set {
                this.issuedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string letter {
            get {
                return this.letterField;
            }
            set {
                this.letterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string phonetic {
            get {
                return this.phoneticField;
            }
            set {
                this.phoneticField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class OFPDestination {
        
        private string icao_codeField;
        
        private string iata_codeField;
        
        private string faa_codeField;
        
        private string icao_regionField;
        
        private string elevationField;
        
        private double pos_latField;
        
        private bool pos_latFieldSpecified;
        
        private double pos_longField;
        
        private bool pos_longFieldSpecified;
        
        private string nameField;
        
        private string timezoneField;
        
        private string plan_rwyField;
        
        private int trans_altField;
        
        private bool trans_altFieldSpecified;
        
        private int trans_levelField;
        
        private bool trans_levelFieldSpecified;
        
        private string metarField;
        
        private string metar_timeField;
        
        private string metar_categoryField;
        
        private string metar_visibilityField;
        
        private string metar_ceilingField;
        
        private string tafField;
        
        private string taf_timeField;
        
        private OFPOriginAtis[] atisField;
        
        private notam[] notamField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string icao_code {
            get {
                return this.icao_codeField;
            }
            set {
                this.icao_codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string iata_code {
            get {
                return this.iata_codeField;
            }
            set {
                this.iata_codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string faa_code {
            get {
                return this.faa_codeField;
            }
            set {
                this.faa_codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string icao_region {
            get {
                return this.icao_regionField;
            }
            set {
                this.icao_regionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string elevation {
            get {
                return this.elevationField;
            }
            set {
                this.elevationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double pos_lat {
            get {
                return this.pos_latField;
            }
            set {
                this.pos_latField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pos_latSpecified {
            get {
                return this.pos_latFieldSpecified;
            }
            set {
                this.pos_latFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double pos_long {
            get {
                return this.pos_longField;
            }
            set {
                this.pos_longField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pos_longSpecified {
            get {
                return this.pos_longFieldSpecified;
            }
            set {
                this.pos_longFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string timezone {
            get {
                return this.timezoneField;
            }
            set {
                this.timezoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string plan_rwy {
            get {
                return this.plan_rwyField;
            }
            set {
                this.plan_rwyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int trans_alt {
            get {
                return this.trans_altField;
            }
            set {
                this.trans_altField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool trans_altSpecified {
            get {
                return this.trans_altFieldSpecified;
            }
            set {
                this.trans_altFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int trans_level {
            get {
                return this.trans_levelField;
            }
            set {
                this.trans_levelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool trans_levelSpecified {
            get {
                return this.trans_levelFieldSpecified;
            }
            set {
                this.trans_levelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string metar {
            get {
                return this.metarField;
            }
            set {
                this.metarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string metar_time {
            get {
                return this.metar_timeField;
            }
            set {
                this.metar_timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string metar_category {
            get {
                return this.metar_categoryField;
            }
            set {
                this.metar_categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string metar_visibility {
            get {
                return this.metar_visibilityField;
            }
            set {
                this.metar_visibilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string metar_ceiling {
            get {
                return this.metar_ceilingField;
            }
            set {
                this.metar_ceilingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string taf {
            get {
                return this.tafField;
            }
            set {
                this.tafField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string taf_time {
            get {
                return this.taf_timeField;
            }
            set {
                this.taf_timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OFPOriginAtis[] atis
        {
            get
            {
                return this.atisField;
            }
            set
            {
                this.atisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("notam")]
        public notam[] notam {
            get {
                return this.notamField;
            }
            set {
                this.notamField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class OFPAlternate {
        
        private string icao_codeField;
        
        private string iata_codeField;
        
        private string faa_codeField;
        
        private string icao_regionField;
        
        private string elevationField;
        
        private double pos_latField;
        
        private bool pos_latFieldSpecified;
        
        private double pos_longField;
        
        private bool pos_longFieldSpecified;
        
        private string nameField;
        
        private string timezoneField;
        
        private string plan_rwyField;
        
        private int trans_altField;
        
        private bool trans_altFieldSpecified;
        
        private int trans_levelField;
        
        private bool trans_levelFieldSpecified;
        
        private string cruise_altitudeField;
        
        private string distanceField;
        
        private string gc_distanceField;
        
        private string air_distanceField;
        
        private string track_trueField;
        
        private string track_magField;
        
        private string tasField;
        
        private string gsField;
        
        private string avg_wind_compField;
        
        private string avg_wind_dirField;
        
        private string avg_wind_spdField;
        
        private string avg_tropopauseField;
        
        private string avg_tdvField;
        
        private string eteField;
        
        private string burnField;
        
        private string routeField;
        
        private string route_ifpsField;
        
        private string metarField;
        
        private string metar_timeField;
        
        private string metar_categoryField;
        
        private string metar_visibilityField;
        
        private string metar_ceilingField;
        
        private string tafField;
        
        private string taf_timeField;
        
        private notam[] notamField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string icao_code {
            get {
                return this.icao_codeField;
            }
            set {
                this.icao_codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string iata_code {
            get {
                return this.iata_codeField;
            }
            set {
                this.iata_codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string faa_code {
            get {
                return this.faa_codeField;
            }
            set {
                this.faa_codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string icao_region {
            get {
                return this.icao_regionField;
            }
            set {
                this.icao_regionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string elevation {
            get {
                return this.elevationField;
            }
            set {
                this.elevationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double pos_lat {
            get {
                return this.pos_latField;
            }
            set {
                this.pos_latField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pos_latSpecified {
            get {
                return this.pos_latFieldSpecified;
            }
            set {
                this.pos_latFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double pos_long {
            get {
                return this.pos_longField;
            }
            set {
                this.pos_longField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pos_longSpecified {
            get {
                return this.pos_longFieldSpecified;
            }
            set {
                this.pos_longFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string timezone {
            get {
                return this.timezoneField;
            }
            set {
                this.timezoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string plan_rwy {
            get {
                return this.plan_rwyField;
            }
            set {
                this.plan_rwyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int trans_alt {
            get {
                return this.trans_altField;
            }
            set {
                this.trans_altField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool trans_altSpecified {
            get {
                return this.trans_altFieldSpecified;
            }
            set {
                this.trans_altFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int trans_level {
            get {
                return this.trans_levelField;
            }
            set {
                this.trans_levelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool trans_levelSpecified {
            get {
                return this.trans_levelFieldSpecified;
            }
            set {
                this.trans_levelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cruise_altitude {
            get {
                return this.cruise_altitudeField;
            }
            set {
                this.cruise_altitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gc_distance {
            get {
                return this.gc_distanceField;
            }
            set {
                this.gc_distanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string air_distance {
            get {
                return this.air_distanceField;
            }
            set {
                this.air_distanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string track_true {
            get {
                return this.track_trueField;
            }
            set {
                this.track_trueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string track_mag {
            get {
                return this.track_magField;
            }
            set {
                this.track_magField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tas {
            get {
                return this.tasField;
            }
            set {
                this.tasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gs {
            get {
                return this.gsField;
            }
            set {
                this.gsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string avg_wind_comp {
            get {
                return this.avg_wind_compField;
            }
            set {
                this.avg_wind_compField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string avg_wind_dir {
            get {
                return this.avg_wind_dirField;
            }
            set {
                this.avg_wind_dirField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string avg_wind_spd {
            get {
                return this.avg_wind_spdField;
            }
            set {
                this.avg_wind_spdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string avg_tropopause {
            get {
                return this.avg_tropopauseField;
            }
            set {
                this.avg_tropopauseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string avg_tdv {
            get {
                return this.avg_tdvField;
            }
            set {
                this.avg_tdvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ete {
            get {
                return this.eteField;
            }
            set {
                this.eteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string burn {
            get {
                return this.burnField;
            }
            set {
                this.burnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string route {
            get {
                return this.routeField;
            }
            set {
                this.routeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string route_ifps {
            get {
                return this.route_ifpsField;
            }
            set {
                this.route_ifpsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string metar {
            get {
                return this.metarField;
            }
            set {
                this.metarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string metar_time {
            get {
                return this.metar_timeField;
            }
            set {
                this.metar_timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string metar_category {
            get {
                return this.metar_categoryField;
            }
            set {
                this.metar_categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string metar_visibility {
            get {
                return this.metar_visibilityField;
            }
            set {
                this.metar_visibilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string metar_ceiling {
            get {
                return this.metar_ceilingField;
            }
            set {
                this.metar_ceilingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string taf {
            get {
                return this.tafField;
            }
            set {
                this.tafField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string taf_time {
            get {
                return this.taf_timeField;
            }
            set {
                this.taf_timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("notam")]
        public notam[] notam {
            get {
                return this.notamField;
            }
            set {
                this.notamField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class NewDataSet
    {
        partial class destinationDataTable
        {
        }

        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OFP", typeof(OFP))]
        [System.Xml.Serialization.XmlElementAttribute("fix", typeof(fix))]
        [System.Xml.Serialization.XmlElementAttribute("notam", typeof(notam))]
        [System.Xml.Serialization.XmlElementAttribute("pdf", typeof(pdf))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
}
