name: Build with version from tag

on:
  create:
    tags:
      - '*'
      
jobs:
  build:
    runs-on: windows-latest

    steps:
       
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'  # Adjust the version if needed

    - name: Get latest tag pushed
      id: previoustag
      uses: oprypin/find-latest-tag@v1
      with:
        repository: Skall34/SimAddon
        releases-only: false
    
    - name: Get the version from tag
      id: get_version
      run: echo ::set-output name=VERSION::${{ steps.previoustag.outputs.tag }}

    - name: set version in assembly
      id: update
      uses: vers-one/dotnet-project-version-updater@v1.6
      with:
        file: "SimAddon/SimAddon.csproj"
        version: ${{ steps.previoustag.outputs.tag }}

    - name: set version in installer
      shell: pwsh
      run: ./updateVersion.ps1 ${{ steps.previoustag.outputs.tag }}

    - name: Build the solution
      run: dotnet build SimAddon.sln --configuration Release

    - name: publish the SimAddonLogger project
      run: dotnet publish Logger/SimAddonLogger.csproj --configuration Release --output publish_output

    - name: publish the SimAddonDataManager project
      run: dotnet publish SimDataManager/SimDataManager.csproj --configuration Release --output publish_output

    - name: publish the SimAddonPlugin project
      run: dotnet publish plugins/SimAddonPLugin/SimAddonPlugin.csproj --configuration Release --output publish_output

    - name: publish the SimAddon project
      run: dotnet publish SimAddon/SimAddon.csproj --configuration Release --output publish_output

    - name: publish FlightRec plugin
      run: dotnet publish plugins/FlightRecPlugin/FlightRecPlugin.csproj --configuration Release --output publish_output\plugins\FlightRecorder

    - name: publish Bushtrip plugin
      run: dotnet publish plugins/BushtripPlugin/BushtripPlugin.csproj --configuration Release --output publish_output\plugins\Bushtrip

    - name: publish meteo plugin
      run: dotnet publish plugins/MeteoPlugin/MeteoPlugin.csproj --configuration Release --output publish_output\plugins\Meteo

#    - name: Setup VS Dev Environment
#      uses: seanmiddleditch/gha-setup-vsdevenv@v4
      
#    - name: Build vdproj installer
#      run: devenv installer.vdproj /build release

#    - name: Compile .ISS to .EXE Installer
#      uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
#      with:
#        path: Setup/Flight_Recorder.iss
#        options: /O+

#    #rem sign OK, but verify fails because auto-signed
#    - name: sign setup
#      uses: GabrielAcostaEngler/signtool-code-sign@1.0.6
#      with:
#       certificate: '${{ secrets.CERTIFICATE }}'
#       cert-password: '${{ secrets.PASSWORD }}'
#       cert-sha1: '${{ secrets.SHA1 }}'
#       cert-description: 'Skywing'
#       folder: 'Build'
#       recursive: false
#       timestamp-server: 'http://timestamp.digicert.com'

#    - name: Publish the project
#      run: dotnet publish FlightRecorder.csproj --configuration Release --output publish_output

    - name: Upload archive
      uses: actions/upload-artifact@v4.4.3
      with:
        name: SimAddon_${{ steps.previoustag.outputs.tag }}
        path: publish_output

#    - name: Upload setup
#      uses: actions/upload-artifact@v2
#      with:
#        name: flight_recorder_setup_${{ steps.previoustag.outputs.tag }}
#        path: Build/flight_recorder_setup_${{ steps.previoustag.outputs.tag }}.exe
