name: Build with version from tag

on:
  create:
    tags:
      - '*'
      
jobs:
  build:
    runs-on: windows-latest

    steps:
       
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'  # Adjust the version if needed

    - name: Get latest tag pushed
      id: previoustag
      uses: oprypin/find-latest-tag@v1
      with:
        repository: Skall34/SimAddon
        releases-only: false
    
    - name: Get the version from tag
      id: get_version
      run: echo ::set-output name=VERSION::${{ steps.previoustag.outputs.tag }}

    - name: set version in assembly
      id: update
      uses: vers-one/dotnet-project-version-updater@v1.6
      with:
        file: "SimAddon/SimAddon.csproj"
        version: ${{ steps.previoustag.outputs.tag }}

    - name: set version in installer
      shell: pwsh
      run: ./updateVersion.ps1 ${{ steps.previoustag.outputs.tag }}

    - name: Build the solution
      run: dotnet build SimAddon.sln --configuration Release

    - name: publish the SimAddonLogger project
      run: dotnet publish Logger/SimAddonLogger.csproj --configuration Release --output publish_output

    - name: publish the SimAddonDataManager project
      run: dotnet publish SimDataManager/SimDataManager.csproj --configuration Release --output publish_output

    - name: publish the SimAddonPlugin project
      run: dotnet publish plugins/SimAddonPLugin/SimAddonPlugin.csproj --configuration Release --output publish_output

    - name: publish the SimAddon project
      run: dotnet publish SimAddon/SimAddon.csproj --configuration Release --output publish_output

    - name: publish FlightRec plugin
      run: dotnet publish plugins/FlightRecPlugin/FlightRecPlugin.csproj --configuration Release --output publish_output\plugins\0_FlightRecorder

    - name: publish Bushtrip plugin
      run: dotnet publish plugins/BushtripPlugin/BushtripPlugin.csproj --configuration Release --output publish_output\plugins\1_Bushtrip

    - name: publish meteo plugin
      run: dotnet publish plugins/MeteoPlugin/MeteoPlugin.csproj --configuration Release --output publish_output\plugins\2_Meteo

    - name: publish ATIS plugin
      run: dotnet publish plugins/ATISPlugin/ATISPlugin.csproj --configuration Release --output publish_output\plugins\3_ATIS

    - name: publish Chartfox plugin
      run: dotnet publish plugins/ChartFoxPlugin/ChartFoxPlugin.csproj --configuration Release --output publish_output\plugins\4_ChartFox

    - name: publish Vatsim radar plugin
      run: dotnet publish plugins/VatsimRadarPlugin/VatsimRadarPlugin.csproj --configuration Release --output publish_output\plugins\5_ATC

    - name: publish Comm plugin
      run: dotnet publish plugins/CommPlugin/CommPlugin.csproj --configuration Release --output publish_output\plugins\6_Comm
      
    - name: Upload archive
      uses: actions/upload-artifact@v4.4.3
      with:
        name: SimAddon_zip_${{ steps.previoustag.outputs.tag }}
        path: publish_output

    #- name: Setup VS Dev Environment
    #  uses: seanmiddleditch/gha-setup-vsdevenv@v4
      
    #- name: Build vdproj installer
    #  run: devenv installer/installer.vdproj /build release

    #- name: Upload setup
    #  uses: actions/upload-artifact@v4.4.3
    #  with:
    #    name: simaddon_setup_${{ steps.previoustag.outputs.tag }}
    #    compression-level: 0
    #    path: setup/*.*


    #   uses: repolevedavaj/install-nsis@v1.0.2
    #   with:
    #     nsis-version: '3.11'

    #- name: compile nsis setup
    #  run: makensis /V4 nsis/installer.nsi   

    - name: compile nsis setup
      uses: joncloud/makensis-action@v4
      with:
        script-file: nsis/installer.nsi

    - name: upload nsis installer
      uses: actions/upload-artifact@v4.4.3
      with:
        name: simaddon_setup_${{ steps.previoustag.outputs.tag }}
        compression-level: 0
        path: nsis/simaddon_setup_*.exe
