name: Autobuild & test from code push

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '.github/**'     
    branches:
      - main  # Adjust the branch name if needed

jobs:
  build:
    runs-on: windows-latest
    

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'  # Adjust the version if needed

    - name: Build the solution
      run: dotnet build SimAddon.sln --configuration Release

#    - name: Build the SimAddonLogger project
#      run: dotnet build Logger/SimAddonLogger.csproj --configuration Release

#    - name: Build the SimAddonDataManager project
#      run: dotnet build SimDataManager/SimDataManager.csproj --configuration Release

#    - name: Build the SimAddonPlugin project
#      run: dotnet build plugins/SimAddonPLugin/SimAddonPlugin.csproj --configuration Release

#    - name: Build the project
#      run: dotnet build SimAddon/SimAddon.csproj --configuration Release

#    - name: Build FlightRec plugin
#      run: dotnet build plugins/FlightRecPlugin/FlightRecPlugin.csproj --configuration Release

#    - name: Setup VS Dev Environment
#      uses: seanmiddleditch/gha-setup-vsdevenv@v4
      
#    - name: Build vdproj installer
#      run: devenv installer.vdproj /build release
      
    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test

    - name: Publish the project
      run: dotnet publish --configuration Release --output publish_output /p:EnableWindowsTargeting=true

    - name: Upload zip artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: flight_recorder
        path: publish_output/*
